# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_post',
            field=models.BooleanField(default=False),
        ),
    ]
