# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-15 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='roll_no',
            field=models.IntegerField(blank=True, default=160123005),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='profile_img',
            field=models.ImageField(default='profile_img/profile.png', upload_to='profile_img'),
        ),
    ]
