# Generated by Django 2.0.3 on 2018-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_auto_20180314_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='phone_no',
            field=models.IntegerField(blank=True, default=999999999),
        ),
    ]
