# Generated by Django 2.0.3 on 2018-03-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alumni_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='email_link',
            field=models.URLField(null=True),
        ),
    ]
