# Generated by Django 2.0.3 on 2018-03-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_alumni_email_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='email_link',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
